#pragma once

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define TILE_COUNT 3
#define BACKGROUND_COUNT 1

#define TILE_WIDTH 128
#define TILE_HEIGHT 128

#define TILEMAP_WIDTH 34
#define TILEMAP_HEIGHT 8

#define MAP_WIDTH TILEMAP_WIDTH * TILE_WIDTH
#define MAP_HEIGHT TILEMAP_HEIGHT * TILE_HEIGHT

